Wl 32
cadeca/vitele-be pull request #2
Opened 2020-09-09 21:03 UTC by nagyDarius

2020-09-09 21:20 UTC, MarioRivis requested changes
Why do we need these props in application-prod.yml?

2020-09-10 13:22 UTC, nagyDarius commented
> Why do we need these props in application-prod.yml?

Because: 
- dialect: org.hibernate.dialect.PostgreSQLDialect is for generating a more efficient SQL for postgres
- the driver for the production database is prety clear

and we used this prod environment for integration tests as well, so that's why I added it already

2020-09-10 20:01 UTC, MarioRivis requested changes

2020-09-10 20:01 UTC, MarioRivis commented on src/intTest/kotlin/ro/cadeca/weasylearn/BasePostgreSQLContainerIT.kt
> +@ActiveProfiles(profiles = ["prod"])
integrationTest

2020-09-10 20:01 UTC, MarioRivis commented on build.gradle.kts
> +	testRuntimeOnly("org.postgresql:postgresql")
remove

2020-09-10 20:29 UTC, MarioRivis approved these changes

2020-09-10 20:30 UTC, merged