WL-18 Added CI github workflows
cadeca/vitele-be pull request #3
Opened 2020-09-10 19:00 UTC by nagyDarius

2020-09-10 20:04 UTC, MarioRivis requested changes

2020-09-10 20:04 UTC, MarioRivis commented on .github/workflows/assemble.yml
> +        run: gradle assemble
gradle build -X integrationTest

2020-09-10 20:04 UTC, MarioRivis commented on .github/workflows/assemble.yml
> +name: Assemble
Build

2020-09-10 20:04 UTC, MarioRivis commented on .github/workflows/build.yml
> +name: Build
Rename files also -> Release

2020-09-10 20:04 UTC, MarioRivis commented on .github/workflows/build.yml
> +  build:
job also

2020-09-10 20:04 UTC, MarioRivis commented on .github/workflows/build.yml
> +        run: gradle build
add release to github packages as comment! TODO!!!

2020-09-10 20:15 UTC, nagyDarius commented on .github/workflows/build.yml
> +name: Build
Renamed to integration test

2020-09-10 20:49 UTC, MarioRivis approved these changes

2020-09-10 20:49 UTC, merged

2020-09-11 16:30 UTC, MarioRivis requested changes

2020-09-11 16:30 UTC, MarioRivis commented on .github/workflows/build.yml
> +        run: gradle build -x integrationTest
add clean?

2020-09-11 16:30 UTC, MarioRivis commented on .github/workflows/integrationTest.yml
> +        run: gradle build
add clean?