Wl 42
cadeca/vitele-be pull request #7
Opened 2020-09-16 20:18 UTC by AndyMolin

2020-09-18 11:22 UTC, nagyDarius submitted a review, later dismissed

2020-09-20 17:01 UTC, MarioRivis requested changes

2020-09-20 17:01 UTC, MarioRivis commented on src/main/kotlin/ro/cadeca/weasylearn/controllers/UserController.kt
> +    @GetMapping("allTeachers")
change to only one request param and get users based on that value (Bad request if param is not Student, Teacher, User or All)

2020-09-20 17:01 UTC, MarioRivis commented on src/main/kotlin/ro/cadeca/weasylearn/services/UserService.kt
> +        userRepository.findAll().iterator().forEach {
don't get all users, use query to get them (method in Repository)

2020-09-21 19:42 UTC, nagyDarius approved these changes

2020-09-21 19:44 UTC, MarioRivis approved these changes

2020-09-21 19:44 UTC, merged